apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logz
spec:
  replicas: 2
  selector:
    matchLabels:
      name: logz
  template:
    metadata:
      labels:
        name: logz
    spec:
      containers:
      - name: logz
        image: eu.gcr.io/tuleyprod/logz:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: PROJECT_ID
          value: tuleyprod
        - name: PUBSUB_TOPIC
          value: gke-logs
        - name: UPLOAD_URL
          value: https://listener.logz.io:8071?token=redacted